### PR TITLE
Unconscious AI - fix

### LINKED ISSUE #23: Enemies not dying after getting shot
Hi,

Iam back!

Tried the latest commit. Some enemies are stuck in deathless limbo after successfully shooting them.
They are down but can move their heads/torsos but never wake up. After they get into this state nothing is harming them further but they appear to never wake up.

### PR DESCRIPTION
**Pull request by SomethingSimpl**
Fixes #23

### CODE REVIEW

**Comment by LordGolias** [comment]
Doesn't this makes all AI units non-revivable? I though we wanted them to be revivable but that would die if sufficiently shoot at while unconscious.

**Comment by SomethingSimpl** [comment]
Hm, do we really need this for AI? I get that its useful when you have some recruits in SP but ACE Medical is having trouble with the "sufficiently shoot at while unconscious" part. The ACE Medical module is undergoing a rewrite that should fix this issue, but meanwhile there is no way to kill the downed "unconscious" units as far as Iam aware.

Thats why I think for the time being its just easiest to not have the AI be "unconscious upon taking lethal damage".

**Comment by LordGolias** [comment]
I was able to solve it without disabling the revive for AIs. :) Thanks for the PR and thanks for the help!

**Comment by SomethingSimpl** [comment]
Nice job! Thats actually really cool. But Id keep the option to turn the AI unconsciousness in the parameters of the mission either way, more power to the user! :)

**Pull request closed without merging**
