### PR TITLE
Develop branch changes

### PR DESCRIPTION
**Pull request by jlillis**
This PR contains various fixes to clean up some scripts and make the mission more playable. Changes:

- Fixed a few typos
- Removed player map markers & nametags (servers should use a mod for this functionality, i.e ACE)
- Removed the music script
- Fixed a small bug in the CDF (RHS) faction template, making it available as a playable faction again.
- Added the Toolkit to the default unlocked items list
- Fixed save/load game functionality on dedicated servers
    - Previous savegames are no longer compatible
    - Saves on dedicated servers are saved in the server's profile
    - Saves can no longer be copied to/from clipboard
- Fixed being unable to respawn with ACE medical
- Fixed tasks not appearing for JIP/respawned players
- Disabled AI unconsciousness (temporary change until medical stuff gets looked at)

### CODE REVIEW

**Comment by LordGolias** [comment]
Thanks a lot for this PR. Looks very solid to me.

There are a couple of things that deserve some comments. I will comment on a commit basis, because your commits are very much independent of each other (which is great).

* 5c73a18: agree
* 63d4acc and 20fd1e5: I would remove both commits (I can do this myself)
* 1decc5c: agree
* 189070b: do not agree. Could you clarify why Altis should be the default?
* d30dffa: agree
* 3839b27: I would amend d30dffa directly (I can do this myself)
* 2925bfd: agree
* 03c8bec: agree
* 07f648b: agree
* 1c93c6d: agree
* e389b86: I would amend 07f648b directly
* a267d25 and 39af2b3: I would remove both commits (I can do this myself)
* 3ddddc4: agree. Did you tested that this works both with and without ACE?
* f5c02aa: I would amend 07f648b directly

* dbae3e5 (save game changes): I haven't checked this one in detail, I think that I agree with it conceptually, but still not sure about it.
* 1e1962f: I am not sure I agree with it. Could you clarify the why?

Regardless, great work here @jlillis!

**Comment by jlillis** [comment]
189070bed1e765ce76fb8a08dd541bc2bb0d6527: forgot I did that. I renamed that file since I used Altis to test these changes. Haven't really touched Tanoa at all, but I would assume it works the same. As for whether or not it should be the default: alphabetical order?

3ddddc4116d81fa30160685cc1c005a4547e7ba8: the only change I noticed without ACE was the 10 second respawn timer. 

dbae3e5fd676c1ff43b28789aefa979fa3f562a6: There is probably more work that could be done here - I noticed that there seemed to be some code for migrating saves from previous "versions", but I wasn't sure what to do with it. Saving/loading to & from clipboard could be made to work again in SP and MP if we give users a dialog box to CTRL+C/CTRL+V the save data from (working around the limitations of the clipboard functions).

1e1962f0f031883d254a144393978c23fa5a9062: I made this change because I was getting frustrated with being unable to kill unconscious enemies, both with and without ACE. It's really just a quick hack. There are other changes I had in mind for the medical system in general, but for now I wanted to be able to kill things quickly to test other changes.

A few questions:

- Are there many people still testing this? It seems like the antistasi site has been down for a few days, and even before then it looks like they're focusing on their community version. I much prefer working on this version since the code is generally cleaner (thanks for that).

- Is SP and vanilla compatibility still considered a "must" for Antistasi? Playing this mission alone does not sound like fun. I've also opened [a branch](https://github.com/jlillis/antistasi/commits/cba-ai-refactor) to test replacing UPSMON functions with CBA's AI functions (i.e [CBA_fnc_taskAttack](https://cbateam.github.io/CBA_A3/docs/files/ai/fnc_taskAttack-sqf.html#CBA_fnc_taskAttack)). It's playable but there is still a lot of tweaking and testing to do - probably more than I can do alone.

**Comment by LordGolias** [comment]
I merged most of the commits, with the changes I mentioned, apart from the 2 commits I mentioned needed some discussion.

The 189070b I dropped it since there is no advantage in using a default one, and IMO it is better to be explicit and force the player that does not download the mission from steam workshop to rename the mission itself.

The dbae3e5 I dropped for now because it breaks save compatibility, which I am trying to keep in this 0.2 version. I agree with most of your semantic changes, but keeping saved games is a requirement I imposed for 0.2v at some point now.

The point of the migrations is just that: a way to migrate old saved games to new ones. This follows the same principles of [Alembic](http://alembic.zzzcomputing.com/en/latest/) or [Django migrations](https://docs.djangoproject.com/en/2.0/topics/migrations/) (for relational databases).

1e1962f: I understand, and I agree with you that it is very frustrating. However, this is not a fix, specially for SP where your AI team is very important.

> Are there many people still testing this?

I do not know. I had to leave the project for about a month, and @StefArma probably switched back to the original, since this one is still unstable. I will be more active again.

> Is SP still considered a "must" for Antistasi?

I know some people that play SP, so, generally, I am trying to keep it. Where do you see that keeping SP hinders development? I made some effort to keep the SP initialization as close as possible to MP.

> Is vanilla compatibility still considered a "must" for Antistasi?

Not sure. For me, no, specially if CBA brings considerable reduction of the code base. The big thing is that most people use steam workshop anyway, so we just need to add a dependency to workshop CBA (assuming that this is easy to do)

**Comment by jlillis** [comment]
RE 189070b: would it make sense to add mission.sqm to .gitignore?

I can take a second look at the save/load changes in dbae3e5 and either setup a migration or make the saves compatible.

RE singleplayer compatibility - it just struck me as odd that someone would chose to play this alone rather than with a few friends at least - designing features around/testing for singleplayer dosen't seem worth the effort to me. I can't think of a technical reason the mission can't be SP compatible for now though.

RE 1e1962f: I'll take a second look at this soon. Probably best to make a separate issue and PR for medical related issues.

**Comment by LordGolias** [comment]
Added to gitignore.

Let us bring the save/load functionality discussion to a new issue, I created the #174 for that. :)

**Comment by jlillis** [comment]
Sounds good. Time to close this PR?

**Comment by LordGolias** [comment]
I think so, but feel free to keep the 3 commits you did on a different branch and rebase on top of develop. We may re-use some of them! :)

**Comment by SomethingSimpl** [comment]
Hey gents, just wanted to let you know that your effort is very much appreciated and even though I was MIA for some time now Iam going to do a big thorough test of Antistasi in its current state today and over the weekend.

**Comment by StefArma** [comment]
I can offer a server if you need

**Comment by SomethingSimpl** [comment]
Oh really? That would be awesome! How can we set this up?

**Comment by StefArma** [comment]
Add me on Steam http://steamcommunity.com/profiles/76561198005296652/

and join me on TS: antistasi.enjinvoice.com

**Comment by jlillis** [comment]
Going to go ahead and close PR, since the save/load changes discussed have been already been merged.

**Pull request closed without merging**
