### PR TITLE
Fix/dedicated server/hq items placement

### PR DESCRIPTION
**Pull request by JohnnyDeeee**
It looks like this code fixes the issue created [here](https://github.com/LordGolias/antistasi/issues/11).

The problem was that every HQ item was given the position of the camp fire as a center point for finding a position in a certain radius.

What i did was just wait untill the campfire actually moved to its new position and only then continue the code.

This code was testen on:
- Dedicated server
- Non-Dedicated server (ran through Eden editor)
- SinglePlayer (ran through Eden editor)

### CODE REVIEW

**Comment by LordGolias** [comment]
Hey @JohnnyDeeee, understanding what is happening is a great finding, and super not trivial! 

Your solution fixes the issue, but I am not sure we need to add a `waituntil` for the `fuego` to be placed. Can't we just create the central position and create every object around it, without relying on `getPos fuego`? I created [a commit](https://github.com/LordGolias/antistasi/commit/603755a25f34888cf396be07ff2d3a5aa7b5e7bf) with these changes on a new branch to describe what I meant. That branch is branched from a major WIP, so do not branch from it if you plan to commit to master directly.

If you agree with this approach, can you create a new PR (against master) with that? You should be committing because the very hard part was to identify the root cause of this.

**Comment by JohnnyDeeee** [comment]
> Can't we just create the central position and create every object around it

> I created a commit with these changes on a new branch to describe what I meant

You used Petros his position as a center point? The thing is, when you use the campfire as a center point it looks kinda nice (like a real small camp). But when using petros as a center point it looks weird to me..

This is just a personal preferrence and if you think using Petros as a center is better for performance than i would agree.

**Comment by LordGolias** [comment]
I was thinking more in 
1. define the center position
2. put the fire on it
3. put the box 1 around it
4. put map around it
...

instead of 

1. put the fire on center position
2. put the box 1 around it
3. put map around it

In the latter case, 2 depends on the fire being placed. On the former case, 3 does not depend on the fire being placed. The objects are just placed independently on of the other.

**Comment by JohnnyDeeee** [comment]
Ah i see. That would be better yeah.

**Comment by JohnnyDeeee** [comment]
Cant reproduce so i guess it is fixed (https://github.com/LordGolias/antistasi/issues/11)

**Pull request closed without merging**
